/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type InferJson = {
  bug_class: string;
  kind: string;
  bug_type: string;
  qualifier: string;
  severity: string;
  visibility: string;
  line: number;
  column: number;
  procedure: string;
  procedure_id: string;
  procedure_start_line: number;
  file: string;
  bug_trace: {
    level: number;
    filename: string;
    line_number: number;
    column_number: number;
    description: string;
    node_tags: {
      tag: string;
      value: string;
      [k: string]: any;
    }[];
    [k: string]: any;
  }[];
  key: number;
  qualifier_tags: {
    tag: string;
    value: string;
    [k: string]: any;
  }[];
  hash: number;
  bug_type_hum: string;
  [k: string]: any;
}[];
